/**
 * Generated by 小🐔小🐔咕咕嘚.
 */
///<reference path="./declarations.d.ts" />
require("../env");
import * as React from "react"
import {getStore, history, RootState} from "./bootstrap";
require('./main.css');
require('./register-service-worker');
require("./config/form")
require.ensure(["./config/routes.tsx","guguder"],function(){
    const {App} = require("guguder");
    const ReactDOM = require("react-dom");
    const {rootRoutes} = require("./config/routes.tsx");
    ReactDOM.render(
        <App store={getStore() as any} history={history} routes={rootRoutes} />,
        document.querySelector("#root")
    )
},()=>{},"core");

declare const module:any;

if(module.hot) {
    module.hot.accept(['./config/routes.tsx',"guguder"],function(){
        const {rootRoutes} = require("./config/routes.tsx");
        const ReactDOM = require("react-dom");
        const {App} = require("guguder");
        ReactDOM.render(
            <App store={getStore() as any} history={history} routes={rootRoutes} />,
            document.querySelector("#root")
        )
    })
}